In [1]:
import numpy as np

In [2]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
np.sum(x, axis=0) #axis는 쉽게 말해 축

105

In [4]:
y = x.reshape(3,5)
print(y)
np.sum(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


105

In [5]:
y = x.reshape(3,5)
print(y)
np.sum(y, axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([15, 18, 21, 24, 27])

In [6]:
y = x.reshape(3,5)
print(y)
np.sum(y, axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([10, 35, 60])

In [10]:
z= np.arange(36).reshape(3,4,3)
print(z)
np.sum(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


630

In [11]:
z= np.arange(36).reshape(3,4,3)
print(z)
np.sum(z, axis=0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[36, 39, 42],
       [45, 48, 51],
       [54, 57, 60],
       [63, 66, 69]])

In [12]:
z= np.arange(36).reshape(3,4,3)
print(z)
np.sum(z, axis=1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


array([[ 18,  22,  26],
       [ 66,  70,  74],
       [114, 118, 122]])

In [13]:
import numpy as np

In [15]:
#shape이 다른 행렬 연산

In [16]:
a = np.arange(12).reshape(4,3)
b = np.arange(100,103)
c = np.arange(1000,1004)
d = b.reshape(1,3)

In [17]:
print(a)
print(b)
print(c)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[100 101 102]
[1000 1001 1002 1003]
[[100 101 102]]


In [18]:
a+b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [26]:
a+c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [27]:
a+d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [28]:
x = np.random.randint(1, 100, size=10)
print(x)

[13 33 85 45 38 25 74 91 71 42]


In [29]:
even_mask = x % 2 ==0
print(even_mask)

[False False False False  True False  True False False  True]


In [30]:
x[even_mask]

array([38, 74, 42])

In [31]:
x[x%2==0]

array([38, 74, 42])

In [32]:
x[x>30]

array([33, 85, 45, 38, 74, 91, 71, 42])

In [33]:
x[(x%2==0) & (x<30)]

array([], dtype=int32)

In [34]:
x[(x<30)|(x>50)]

array([13, 85, 25, 74, 91, 71])

In [35]:
import numpy as np
import pandas as pd

In [36]:
s1 = pd.Series([1,2,3])
s1

0    1
1    2
2    3
dtype: int64

In [37]:
s2 = pd.Series(['a','b','c'])
s2

0    a
1    b
2    c
dtype: object

In [38]:
s3 = pd.Series(np.arange(200))
s3

0        0
1        1
2        2
3        3
4        4
      ... 
195    195
196    196
197    197
198    198
199    199
Length: 200, dtype: int32

In [39]:
s4 = pd.Series([1,2,3], [100, 200, 300])
s4

100    1
200    2
300    3
dtype: int64

In [40]:
s6 = pd.Series(np.arange(5), np.arange(100, 105), dtype=np.int16)
s6

100    0
101    1
102    2
103    3
104    4
dtype: int16

In [41]:
s6.index

Int64Index([100, 101, 102, 103, 104], dtype='int64')

In [42]:
s6.values

array([0, 1, 2, 3, 4], dtype=int16)

In [44]:
s6[104] = 70
s6

100     0
101     1
102     2
103     3
104    70
dtype: int16

In [47]:
s = pd.Series([1,1,2,1,2,2,2,1,1,3,3,4,5,5,7,np.NaN])
s

0     1.0
1     1.0
2     2.0
3     1.0
4     2.0
5     2.0
6     2.0
7     1.0
8     1.0
9     3.0
10    3.0
11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [48]:
len(s)

16

In [49]:
s.size

16

In [50]:
s.shape

(16,)

In [51]:
s.unique()

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [52]:
s[5]

2.0

In [55]:
s.value_counts()

1.0    5
2.0    4
3.0    2
5.0    2
4.0    1
7.0    1
dtype: int64

In [56]:
s[5]

2.0

In [59]:
s[[5,7,8,10]].value_counts()

1.0    2
2.0    1
3.0    1
dtype: int64

In [60]:
s.head(n=7)

0    1.0
1    1.0
2    2.0
3    1.0
4    2.0
5    2.0
6    2.0
dtype: float64

In [61]:
s.tail()

11    4.0
12    5.0
13    5.0
14    7.0
15    NaN
dtype: float64

In [62]:
s = pd.Series(np.arange(100,105), ['a','b','c','d','e'])
s

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [64]:
s['a'] = 200
s

a    200
b    101
c    102
d    103
e    104
dtype: int32

In [65]:
s['k'] = 300
s

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [66]:
s.drop('k')

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [67]:
s

a    200
b    101
c    102
d    103
e    104
k    300
dtype: int64

In [68]:
s.drop('k', inplace=True)

In [69]:
s

a    200
b    101
c    102
d    103
e    104
dtype: int64

In [70]:
s[['a', 'b']] = [300, 900]

In [71]:
s

a    300
b    900
c    102
d    103
e    104
dtype: int64

In [72]:
s1 = pd.Series(np.arange(100, 105))
s1

0    100
1    101
2    102
3    103
4    104
dtype: int32

In [73]:
s1[1:3]

1    101
2    102
dtype: int32

In [77]:
s2 = pd.Series(np.arange(100, 105), ['a', 'c','b','d','e'])
s2

a    100
c    101
b    102
d    103
e    104
dtype: int32

In [78]:
s2['c':'d']

c    101
b    102
d    103
dtype: int32

In [83]:
s = pd.Series(np.arange(10), np.arange(10)+1)
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [81]:
s>5

1     False
2     False
3     False
4     False
5     False
6     False
7      True
8      True
9      True
10     True
dtype: bool

In [82]:
s[s>5]

7     6
8     7
9     8
10    9
dtype: int32

In [84]:
s[s>5]

7     6
8     7
9     8
10    9
dtype: int32